/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_applications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/applications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Detail with masked national IDs; `reveal_national_id=1` shows them (audited). */
        get: operations["admin_applications_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/applications/{id}/audit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Audit history of the application and of its documents (incl. replaced ones). */
        get: operations["admin_applications_audit_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/applications/{id}/notes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Internal notes — never exposed on any doctor endpoint. */
        get: operations["admin_applications_notes_list"];
        put?: never;
        /** @description Internal notes — never exposed on any doctor endpoint. */
        post: operations["admin_applications_notes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/applications/{id}/payment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["admin_applications_payment_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/applications/{id}/transition/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["admin_applications_transition_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/doctors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Members (masked national IDs). Full IDs are revealed only on an application detail. */
        get: operations["admin_doctors_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/doctors/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Members (masked national IDs). Full IDs are revealed only on an application detail. */
        get: operations["admin_doctors_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/fee-schedules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Versions are immutable: changing fees means creating a new version (audited). */
        get: operations["admin_fee_schedules_list"];
        put?: never;
        /** @description Versions are immutable: changing fees means creating a new version (audited). */
        post: operations["admin_fee_schedules_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/fee-schedules/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Versions are immutable: changing fees means creating a new version (audited). */
        get: operations["admin_fee_schedules_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["applications_list"];
        put?: never;
        /** @description Draft for the current fiscal year — 201 when created, 200 with the existing one. */
        post: operations["applications_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/beneficiaries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["applications_beneficiaries_list"];
        put?: never;
        post: operations["applications_beneficiaries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/beneficiaries/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["applications_beneficiaries_destroy"];
        options?: never;
        head?: never;
        patch: operations["applications_beneficiaries_partial_update"];
        trace?: never;
    };
    "/api/v1/applications/{application_id}/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description `POST /applications/{id}/documents/` (multipart). Re-uploading a slot replaces it. */
        post: operations["documents_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["applications_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["applications_partial_update"];
        trace?: never;
    };
    "/api/v1/applications/{id}/fees/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Live server quote while editable; the frozen snapshot once submitted. */
        get: operations["applications_fees_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description DRAFT → SUBMITTED or NEEDS_CORRECTION → SUBMITTED (same reference number). */
        post: operations["applications_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/validation/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description All errors grouped by step (rules 16–17 omitted while drafting) + submit readiness. */
        get: operations["applications_validation_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/callback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/dev/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_dev_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/dev/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_dev_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description `GET` metadata (owner or admin) · `DELETE` (owner, only while editable). */
        get: operations["documents_retrieve"];
        put?: never;
        post?: never;
        /** @description `GET` metadata (owner or admin) · `DELETE` (owner, only while editable). */
        delete: operations["documents_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/content/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description `GET /documents/{id}/content/` — authorized stream, or a 302 to a ≤5-minute SAS. */
        get: operations["documents_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/extract/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description `POST /documents/{id}/extract/` — OCR suggestions for the doctor's own document.
         *     Rate limited per user (OCR_RATE_LIMIT, default 30/hour). Nothing is saved.
         */
        post: operations["documents_extract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description `GET/PATCH /api/v1/profile/` — always the requesting doctor's own profile. */
        get: operations["profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description `GET/PATCH /api/v1/profile/` — always the requesting doctor's own profile. */
        patch: operations["profile_partial_update"];
        trace?: never;
    };
    "/api/v1/reference-data/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reference_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `APPLICATION_CREATED` - Application Created
         *     * `APPLICATION_SUBMITTED` - Application Submitted
         *     * `APPLICATION_RESUBMITTED` - Application Resubmitted
         *     * `APPLICATION_STATUS_CHANGED` - Application Status Changed
         *     * `PAYMENT_STATUS_CHANGED` - Payment Status Changed
         *     * `FEE_SNAPSHOT_CREATED` - Fee Snapshot Created
         *     * `DOCUMENT_UPLOADED` - Document Uploaded
         *     * `DOCUMENT_REPLACED` - Document Replaced
         *     * `DOCUMENT_DELETED` - Document Deleted
         *     * `DOCUMENT_VIEWED` - Document Viewed
         *     * `OCR_REQUESTED` - Ocr Requested
         *     * `ADMIN_APPLICATION_VIEWED` - Admin Application Viewed
         *     * `ADMIN_NOTE_ADDED` - Admin Note Added
         *     * `FEE_SCHEDULE_CHANGED` - Fee Schedule Changed
         *     * `ADMIN_ROLE_GRANTED` - Admin Role Granted
         *     * `NATIONAL_ID_REVEALED` - National Id Revealed
         * @enum {string}
         */
        ActionEnum: "APPLICATION_CREATED" | "APPLICATION_SUBMITTED" | "APPLICATION_RESUBMITTED" | "APPLICATION_STATUS_CHANGED" | "PAYMENT_STATUS_CHANGED" | "FEE_SNAPSHOT_CREATED" | "DOCUMENT_UPLOADED" | "DOCUMENT_REPLACED" | "DOCUMENT_DELETED" | "DOCUMENT_VIEWED" | "OCR_REQUESTED" | "ADMIN_APPLICATION_VIEWED" | "ADMIN_NOTE_ADDED" | "FEE_SCHEDULE_CHANGED" | "ADMIN_ROLE_GRANTED" | "NATIONAL_ID_REVEALED";
        AdminApplicationDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly fiscal_year: number;
            readonly application_type: components["schemas"]["ApplicationTypeEnum"];
            readonly work_status: components["schemas"]["WorkStatusEnum"];
            /** @default DRAFT */
            readonly status: components["schemas"]["ApplicationStatusEnum"];
            readonly payment_status: components["schemas"]["PaymentStatusEnum"];
            readonly reference_number: string | null;
            readonly declaration_name: string;
            /** Format: date-time */
            readonly declaration_accepted_at: string | null;
            readonly fee_snapshot: unknown;
            /** Format: uuid */
            readonly fee_schedule: string | null;
            readonly review_notes: string;
            /** Format: email */
            readonly reviewed_by_email: string;
            /** Format: date-time */
            readonly reviewed_at: string | null;
            /** Format: date-time */
            readonly submitted_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly doctor: components["schemas"]["AdminApplicationDoctor"];
            readonly beneficiaries: components["schemas"]["AdminBeneficiary"][];
            readonly documents: components["schemas"]["DocumentSummary"][];
            readonly allowed_transitions: string[];
            readonly beneficiary_warnings: string[];
        };
        AdminApplicationDoctor: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly full_name: string;
            readonly masked_national_id: string;
            /** Format: date */
            readonly date_of_birth: string | null;
            readonly birth_year: number | null;
            readonly gender: components["schemas"]["GenderEnum"];
            readonly religion: components["schemas"]["ReligionEnum"];
            readonly phone_number: string;
            readonly syndicate_type: components["schemas"]["SyndicateTypeEnum"];
            readonly sub_syndicate: string;
            readonly syndicate_registration_number: string;
            readonly syndicate_registration_year: number | null;
            readonly treatment_card_number: string;
            readonly governorate: string;
            readonly neighborhood: string;
            readonly address: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly national_id: string | null;
        };
        AdminApplicationRow: {
            /** Format: uuid */
            readonly id: string;
            readonly reference_number: string | null;
            readonly fiscal_year: number;
            readonly application_type: components["schemas"]["ApplicationTypeEnum"];
            readonly doctor_name: string;
            readonly masked_national_id: string;
            readonly syndicate_type: string;
            readonly sub_syndicate: string;
            readonly governorate: string;
            readonly status: components["schemas"]["ApplicationStatusEnum"];
            readonly payment_status: components["schemas"]["PaymentStatusEnum"];
            /** Format: date-time */
            readonly submitted_at: string | null;
            readonly total: number | null;
        };
        AdminBeneficiary: {
            /** Format: uuid */
            readonly id: string;
            readonly row_number: number;
            readonly kinship: components["schemas"]["KinshipEnum"];
            readonly full_name: string;
            readonly birth_year: number | null;
            readonly masked_national_id: string;
            readonly national_id: string | null;
            readonly is_active: boolean;
            readonly required_documents: {
                [key: string]: unknown;
            }[];
            readonly documents: components["schemas"]["DocumentSummary"][];
        };
        AdminDoctorDetail: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly full_name: string;
            readonly masked_national_id: string;
            /** Format: date */
            readonly date_of_birth: string | null;
            readonly birth_year: number | null;
            readonly gender: components["schemas"]["GenderEnum"];
            readonly religion: components["schemas"]["ReligionEnum"];
            readonly phone_number: string;
            readonly syndicate_type: components["schemas"]["SyndicateTypeEnum"];
            readonly sub_syndicate: string;
            readonly syndicate_registration_number: string;
            readonly syndicate_registration_year: number | null;
            readonly treatment_card_number: string;
            readonly governorate: string;
            readonly neighborhood: string;
            readonly address: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly applications: components["schemas"]["AdminApplicationRow"][];
        };
        AdminDoctorRow: {
            /** Format: uuid */
            readonly id: string;
            readonly full_name: string;
            /** Format: email */
            readonly email: string;
            readonly masked_national_id: string;
            readonly syndicate_type: components["schemas"]["SyndicateTypeEnum"];
            readonly sub_syndicate: string;
            readonly syndicate_registration_number: string;
            readonly governorate: string;
            readonly phone_number: string;
            readonly applications_count: number;
        };
        AdminNote: {
            /** Format: uuid */
            readonly id: string;
            body: string;
            /** Format: email */
            readonly author_email: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        AdminNoteRequest: {
            body: string;
        };
        AdminStats: {
            fiscal_year: number;
            total: number;
            by_status: {
                [key: string]: number;
            };
            by_payment_status: {
                [key: string]: number;
            };
            receipts_pending: number;
        };
        /**
         * @description Doctor view of an application. EVERY field is read-only here; the only writable fields
         *     are in ApplicationUpdateSerializer (PROMPT.md §2.3 #1, §16.2).
         */
        Application: {
            /** Format: uuid */
            readonly id: string;
            readonly fiscal_year: number;
            readonly application_type: components["schemas"]["ApplicationTypeEnum"];
            readonly work_status: components["schemas"]["WorkStatusEnum"];
            readonly status: components["schemas"]["ApplicationStatusEnum"];
            readonly payment_status: components["schemas"]["PaymentStatusEnum"];
            readonly reference_number: string | null;
            readonly declaration_name: string;
            readonly declaration_accepted: boolean;
            /** Format: date-time */
            readonly declaration_accepted_at: string | null;
            readonly fee_snapshot: unknown;
            /** Format: uuid */
            readonly fee_schedule: string | null;
            readonly review_notes: string;
            /** Format: date-time */
            readonly reviewed_at: string | null;
            /** Format: date-time */
            readonly submitted_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly is_editable: boolean;
            readonly beneficiaries: components["schemas"]["Beneficiary"][];
            readonly documents: components["schemas"]["DocumentSummary"][];
        };
        ApplicationCreateRequest: {
            /** @default FIRST_TIME */
            application_type: components["schemas"]["ApplicationTypeEnum"];
        };
        /**
         * @description * `DRAFT` - مسودة
         *     * `SUBMITTED` - مقدم
         *     * `UNDER_REVIEW` - قيد المراجعة
         *     * `NEEDS_CORRECTION` - يحتاج تصحيح
         *     * `APPROVED` - مقبول
         *     * `REJECTED` - مرفوض
         * @enum {string}
         */
        ApplicationStatusEnum: "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "NEEDS_CORRECTION" | "APPROVED" | "REJECTED";
        /**
         * @description * `FIRST_TIME` - أول مرة
         *     * `ADDITION` - إضافة
         * @enum {string}
         */
        ApplicationTypeEnum: "FIRST_TIME" | "ADDITION";
        AuditEntry: {
            /** Format: uuid */
            readonly id: string;
            readonly action: components["schemas"]["ActionEnum"];
            /** Format: date-time */
            readonly timestamp: string;
            /** Format: uuid */
            readonly user_id: string | null;
            /** Format: email */
            readonly user_email: string;
            readonly object_type: string;
            /** Format: uuid */
            readonly object_id: string | null;
            readonly metadata: unknown;
        };
        Beneficiary: {
            /** Format: uuid */
            readonly id: string;
            readonly row_number: number;
            readonly kinship: components["schemas"]["KinshipEnum"];
            readonly full_name: string;
            readonly birth_year: number | null;
            readonly national_id: string | null;
            readonly is_active: boolean;
            readonly required_documents: {
                [key: string]: unknown;
            }[];
            readonly documents: components["schemas"]["DocumentSummary"][];
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Draft-level shape checks; the beneficiary service applies the business rules. */
        BeneficiaryWriteRequest: {
            row_number?: number;
            kinship?: components["schemas"]["KinshipEnum"] | components["schemas"]["BlankEnum"];
            full_name?: string;
            birth_year?: number | null;
            national_id?: string | null;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        CurrentUser: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly role: components["schemas"]["RoleEnum"];
            readonly display_name: string;
            readonly has_profile: boolean;
        };
        DevLoginRequest: {
            /** Format: email */
            email: string;
            /** @default false */
            create: boolean;
        };
        DevUser: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly role: components["schemas"]["RoleEnum"];
            readonly display_name: string;
        };
        /**
         * @description The doctor's own profile. Derived fields (date of birth) and the Entra email are
         *     read-only; birth year and gender follow the national ID when one is present.
         */
        DoctorProfile: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            full_name?: string;
            national_id?: string | null;
            /** Format: date */
            readonly date_of_birth: string | null;
            birth_year?: number | null;
            gender?: components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"];
            religion?: components["schemas"]["ReligionEnum"] | components["schemas"]["BlankEnum"];
            phone_number?: string;
            syndicate_type?: components["schemas"]["SyndicateTypeEnum"] | components["schemas"]["BlankEnum"];
            sub_syndicate?: string;
            syndicate_registration_number?: string;
            syndicate_registration_year?: number | null;
            treatment_card_number?: string;
            governorate?: components["schemas"]["GovernorateEnum"] | components["schemas"]["BlankEnum"];
            neighborhood?: string;
            address?: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Document metadata. Never the blob name or a storage URL: content is served only through
         *     the authorized `/documents/{id}/content/` endpoint.
         */
        DocumentSummary: {
            /** Format: uuid */
            readonly id: string;
            readonly document_type: components["schemas"]["DocumentTypeEnum"];
            /** Format: uuid */
            readonly beneficiary_id: string | null;
            readonly original_filename: string;
            readonly content_type: string;
            readonly file_size: number;
            readonly scan_status: components["schemas"]["ScanStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            readonly content_url: string;
        };
        /**
         * @description * `NATIONAL_ID_FRONT` - صورة البطاقة (وجه)
         *     * `NATIONAL_ID_BACK` - صورة البطاقة (ظهر)
         *     * `SYNDICATE_ID` - كارنيه النقابة
         *     * `PERSONAL_PHOTO` - صورة العضو الأصلي
         *     * `PAYMENT_RECEIPT` - إيصال الدفع
         *     * `BENEFICIARY_NATIONAL_ID` - بطاقة الرقم القومي
         *     * `BIRTH_CERTIFICATE` - شهادة الميلاد
         *     * `MARRIAGE_CERTIFICATE` - شهادة الزواج
         *     * `INSURANCE_PRINT` - برينت تأميني
         *     * `UNIVERSITY_ID` - كارنيه الجامعة
         *     * `OTHER` - مستند آخر
         * @enum {string}
         */
        DocumentTypeEnum: "NATIONAL_ID_FRONT" | "NATIONAL_ID_BACK" | "SYNDICATE_ID" | "PERSONAL_PHOTO" | "PAYMENT_RECEIPT" | "BENEFICIARY_NATIONAL_ID" | "BIRTH_CERTIFICATE" | "MARRIAGE_CERTIFICATE" | "INSURANCE_PRINT" | "UNIVERSITY_ID" | "OTHER";
        DocumentUploadRequest: {
            /** Format: binary */
            file: string;
            document_type: components["schemas"]["DocumentTypeEnum"];
            /** Format: uuid */
            beneficiary_id?: string | null;
        };
        FeeSchedule: {
            /** Format: uuid */
            readonly id: string;
            fiscal_year: number;
            readonly version: number;
            tier_fees: unknown;
            /**
             * @default [
             *       5,
             *       10,
             *       15
             *     ]
             */
            tier_boundaries: unknown;
            admin_fee_member_only?: number;
            admin_fee_with_beneficiaries?: number;
            age_cap_threshold?: number;
            age_cap_amount?: number;
            registration_year_min?: number;
            readonly is_active: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly locked_at: string | null;
        };
        FeeScheduleRequest: {
            fiscal_year: number;
            tier_fees: unknown;
            /**
             * @default [
             *       5,
             *       10,
             *       15
             *     ]
             */
            tier_boundaries: unknown;
            admin_fee_member_only?: number;
            admin_fee_with_beneficiaries?: number;
            age_cap_threshold?: number;
            age_cap_amount?: number;
            registration_year_min?: number;
        };
        /**
         * @description * `MALE` - ذكر
         *     * `FEMALE` - أنثى
         * @enum {string}
         */
        GenderEnum: "MALE" | "FEMALE";
        /**
         * @description * `القاهرة` - القاهرة
         *     * `الجيزة` - الجيزة
         *     * `الإسكندرية` - الإسكندرية
         *     * `الدقهلية` - الدقهلية
         *     * `البحر الأحمر` - البحر الأحمر
         *     * `البحيرة` - البحيرة
         *     * `الفيوم` - الفيوم
         *     * `الغربية` - الغربية
         *     * `الإسماعيلية` - الإسماعيلية
         *     * `المنوفية` - المنوفية
         *     * `المنيا` - المنيا
         *     * `القليوبية` - القليوبية
         *     * `الوادي الجديد` - الوادي الجديد
         *     * `السويس` - السويس
         *     * `أسوان` - أسوان
         *     * `أسيوط` - أسيوط
         *     * `بني سويف` - بني سويف
         *     * `بورسعيد` - بورسعيد
         *     * `دمياط` - دمياط
         *     * `الشرقية` - الشرقية
         *     * `جنوب سيناء` - جنوب سيناء
         *     * `كفر الشيخ` - كفر الشيخ
         *     * `مطروح` - مطروح
         *     * `الأقصر` - الأقصر
         *     * `قنا` - قنا
         *     * `شمال سيناء` - شمال سيناء
         *     * `سوهاج` - سوهاج
         * @enum {string}
         */
        GovernorateEnum: "القاهرة" | "الجيزة" | "الإسكندرية" | "الدقهلية" | "البحر الأحمر" | "البحيرة" | "الفيوم" | "الغربية" | "الإسماعيلية" | "المنوفية" | "المنيا" | "القليوبية" | "الوادي الجديد" | "السويس" | "أسوان" | "أسيوط" | "بني سويف" | "بورسعيد" | "دمياط" | "الشرقية" | "جنوب سيناء" | "كفر الشيخ" | "مطروح" | "الأقصر" | "قنا" | "شمال سيناء" | "سوهاج";
        /**
         * @description * `MOTHER` - أم
         *     * `FATHER` - أب
         *     * `SON_MINOR` - ابن (18 سنة أو أقل)
         *     * `SON_UNIVERSITY` - ابن (طالب جامعي)
         *     * `SON_GRADUATE` - ابن (خريج)
         *     * `DAUGHTER` - ابنة
         *     * `HUSBAND` - زوج
         *     * `WIFE` - زوجة
         * @enum {string}
         */
        KinshipEnum: "MOTHER" | "FATHER" | "SON_MINOR" | "SON_UNIVERSITY" | "SON_GRADUATE" | "DAUGHTER" | "HUSBAND" | "WIFE";
        Logout: {
            entra_logout_url: string | null;
        };
        Me: {
            user: components["schemas"]["CurrentUser"];
            csrf_token: string;
        };
        OcrSuggestion: {
            /** Format: uuid */
            document_id: string;
            document_type: string;
            fields: {
                [key: string]: unknown;
            };
        };
        PaginatedAdminApplicationRowList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminApplicationRow"][];
        };
        PaginatedAdminDoctorRowList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminDoctorRow"][];
        };
        PaginatedApplicationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Application"][];
        };
        PaginatedAuditEntryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AuditEntry"][];
        };
        PaginatedFeeScheduleList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["FeeSchedule"][];
        };
        /** @description The doctor-editable fields. Anything else in the payload is ignored. */
        PatchedApplicationUpdateRequest: {
            application_type?: components["schemas"]["ApplicationTypeEnum"];
            work_status?: components["schemas"]["WorkStatusEnum"] | components["schemas"]["BlankEnum"];
            declaration_name?: string;
            declaration_accepted?: boolean;
        };
        /** @description Draft-level shape checks; the beneficiary service applies the business rules. */
        PatchedBeneficiaryWriteRequest: {
            row_number?: number;
            kinship?: components["schemas"]["KinshipEnum"] | components["schemas"]["BlankEnum"];
            full_name?: string;
            birth_year?: number | null;
            national_id?: string | null;
        };
        /**
         * @description The doctor's own profile. Derived fields (date of birth) and the Entra email are
         *     read-only; birth year and gender follow the national ID when one is present.
         */
        PatchedDoctorProfileRequest: {
            full_name?: string;
            national_id?: string | null;
            birth_year?: number | null;
            gender?: components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"];
            religion?: components["schemas"]["ReligionEnum"] | components["schemas"]["BlankEnum"];
            phone_number?: string;
            syndicate_type?: components["schemas"]["SyndicateTypeEnum"] | components["schemas"]["BlankEnum"];
            sub_syndicate?: string;
            syndicate_registration_number?: string;
            syndicate_registration_year?: number | null;
            treatment_card_number?: string;
            governorate?: components["schemas"]["GovernorateEnum"] | components["schemas"]["BlankEnum"];
            neighborhood?: string;
            address?: string;
        };
        PaymentReviewRequest: {
            payment_status: components["schemas"]["PaymentStatusEnum"];
            /** @default  */
            note: string;
        };
        /**
         * @description * `NOT_UPLOADED` - لم يتم رفع الإيصال
         *     * `PENDING_REVIEW` - بانتظار التأكيد
         *     * `CONFIRMED` - مؤكد
         *     * `REJECTED` - مرفوض
         * @enum {string}
         */
        PaymentStatusEnum: "NOT_UPLOADED" | "PENDING_REVIEW" | "CONFIRMED" | "REJECTED";
        /**
         * @description * `MUSLIM` - مسلم
         *     * `CHRISTIAN` - مسيحي
         * @enum {string}
         */
        ReligionEnum: "MUSLIM" | "CHRISTIAN";
        /**
         * @description * `DOCTOR` - طبيب
         *     * `ADMIN` - مسؤول
         * @enum {string}
         */
        RoleEnum: "DOCTOR" | "ADMIN";
        /**
         * @description * `PENDING` - قيد الفحص
         *     * `CLEAN` - سليم
         *     * `INFECTED` - مصاب
         *     * `SKIPPED` - لم يتم الفحص
         * @enum {string}
         */
        ScanStatusEnum: "PENDING" | "CLEAN" | "INFECTED" | "SKIPPED";
        /**
         * @description * `HUMAN_MEDICINE` - بشري
         *     * `PHARMACY` - صيدلي
         *     * `DENTISTRY` - أسنان
         *     * `VETERINARY` - بيطري
         * @enum {string}
         */
        SyndicateTypeEnum: "HUMAN_MEDICINE" | "PHARMACY" | "DENTISTRY" | "VETERINARY";
        TransitionRequest: {
            to_status: components["schemas"]["ApplicationStatusEnum"];
            /** @default  */
            review_notes: string;
        };
        /**
         * @description * `WORKING` - يعمل
         *     * `PENSIONER` - معاش
         *     * `DECEASED` - متوفى
         * @enum {string}
         */
        WorkStatusEnum: "WORKING" | "PENSIONER" | "DECEASED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_applications_list: {
        parameters: {
            query?: {
                fiscal_year?: number;
                /**
                 * @description * `القاهرة` - القاهرة
                 *     * `الجيزة` - الجيزة
                 *     * `الإسكندرية` - الإسكندرية
                 *     * `الدقهلية` - الدقهلية
                 *     * `البحر الأحمر` - البحر الأحمر
                 *     * `البحيرة` - البحيرة
                 *     * `الفيوم` - الفيوم
                 *     * `الغربية` - الغربية
                 *     * `الإسماعيلية` - الإسماعيلية
                 *     * `المنوفية` - المنوفية
                 *     * `المنيا` - المنيا
                 *     * `القليوبية` - القليوبية
                 *     * `الوادي الجديد` - الوادي الجديد
                 *     * `السويس` - السويس
                 *     * `أسوان` - أسوان
                 *     * `أسيوط` - أسيوط
                 *     * `بني سويف` - بني سويف
                 *     * `بورسعيد` - بورسعيد
                 *     * `دمياط` - دمياط
                 *     * `الشرقية` - الشرقية
                 *     * `جنوب سيناء` - جنوب سيناء
                 *     * `كفر الشيخ` - كفر الشيخ
                 *     * `مطروح` - مطروح
                 *     * `الأقصر` - الأقصر
                 *     * `قنا` - قنا
                 *     * `شمال سيناء` - شمال سيناء
                 *     * `سوهاج` - سوهاج
                 */
                governorate?: "أسوان" | "أسيوط" | "الأقصر" | "الإسكندرية" | "الإسماعيلية" | "البحر الأحمر" | "البحيرة" | "الجيزة" | "الدقهلية" | "السويس" | "الشرقية" | "الغربية" | "الفيوم" | "القاهرة" | "القليوبية" | "المنوفية" | "المنيا" | "الوادي الجديد" | "بني سويف" | "بورسعيد" | "جنوب سيناء" | "دمياط" | "سوهاج" | "شمال سيناء" | "قنا" | "كفر الشيخ" | "مطروح";
                /**
                 * @description الترتيب
                 *
                 *     * `submitted_at` - Submitted at
                 *     * `-submitted_at` - Submitted at (تنازلي)
                 *     * `reference_number` - Reference number
                 *     * `-reference_number` - Reference number (تنازلي)
                 *     * `status` - Status
                 *     * `-status` - Status (تنازلي)
                 *     * `total` - Total
                 *     * `-total` - Total (تنازلي)
                 */
                ordering?: ("-reference_number" | "-status" | "-submitted_at" | "-total" | "reference_number" | "status" | "submitted_at" | "total")[];
                /** @description رقم الصفحة ضمن النتائج المقسمة. */
                page?: number;
                /** @description عدد النتائج التي يجب إرجاعها في كل صفحة. */
                page_size?: number;
                /**
                 * @description * `NOT_UPLOADED` - لم يتم رفع الإيصال
                 *     * `PENDING_REVIEW` - بانتظار التأكيد
                 *     * `CONFIRMED` - مؤكد
                 *     * `REJECTED` - مرفوض
                 */
                payment_status?: ("CONFIRMED" | "NOT_UPLOADED" | "PENDING_REVIEW" | "REJECTED")[];
                search?: string;
                /**
                 * @description * `DRAFT` - مسودة
                 *     * `SUBMITTED` - مقدم
                 *     * `UNDER_REVIEW` - قيد المراجعة
                 *     * `NEEDS_CORRECTION` - يحتاج تصحيح
                 *     * `APPROVED` - مقبول
                 *     * `REJECTED` - مرفوض
                 */
                status?: ("APPROVED" | "DRAFT" | "NEEDS_CORRECTION" | "REJECTED" | "SUBMITTED" | "UNDER_REVIEW")[];
                sub_syndicate?: string;
                submitted_from?: string;
                submitted_to?: string;
                /**
                 * @description * `HUMAN_MEDICINE` - بشري
                 *     * `PHARMACY` - صيدلي
                 *     * `DENTISTRY` - أسنان
                 *     * `VETERINARY` - بيطري
                 */
                syndicate_type?: "DENTISTRY" | "HUMAN_MEDICINE" | "PHARMACY" | "VETERINARY";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminApplicationRowList"];
                };
            };
        };
    };
    admin_applications_retrieve: {
        parameters: {
            query?: {
                reveal_national_id?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminApplicationDetail"];
                };
            };
        };
    };
    admin_applications_audit_list: {
        parameters: {
            query?: {
                fiscal_year?: number;
                /**
                 * @description * `القاهرة` - القاهرة
                 *     * `الجيزة` - الجيزة
                 *     * `الإسكندرية` - الإسكندرية
                 *     * `الدقهلية` - الدقهلية
                 *     * `البحر الأحمر` - البحر الأحمر
                 *     * `البحيرة` - البحيرة
                 *     * `الفيوم` - الفيوم
                 *     * `الغربية` - الغربية
                 *     * `الإسماعيلية` - الإسماعيلية
                 *     * `المنوفية` - المنوفية
                 *     * `المنيا` - المنيا
                 *     * `القليوبية` - القليوبية
                 *     * `الوادي الجديد` - الوادي الجديد
                 *     * `السويس` - السويس
                 *     * `أسوان` - أسوان
                 *     * `أسيوط` - أسيوط
                 *     * `بني سويف` - بني سويف
                 *     * `بورسعيد` - بورسعيد
                 *     * `دمياط` - دمياط
                 *     * `الشرقية` - الشرقية
                 *     * `جنوب سيناء` - جنوب سيناء
                 *     * `كفر الشيخ` - كفر الشيخ
                 *     * `مطروح` - مطروح
                 *     * `الأقصر` - الأقصر
                 *     * `قنا` - قنا
                 *     * `شمال سيناء` - شمال سيناء
                 *     * `سوهاج` - سوهاج
                 */
                governorate?: "أسوان" | "أسيوط" | "الأقصر" | "الإسكندرية" | "الإسماعيلية" | "البحر الأحمر" | "البحيرة" | "الجيزة" | "الدقهلية" | "السويس" | "الشرقية" | "الغربية" | "الفيوم" | "القاهرة" | "القليوبية" | "المنوفية" | "المنيا" | "الوادي الجديد" | "بني سويف" | "بورسعيد" | "جنوب سيناء" | "دمياط" | "سوهاج" | "شمال سيناء" | "قنا" | "كفر الشيخ" | "مطروح";
                /**
                 * @description الترتيب
                 *
                 *     * `submitted_at` - Submitted at
                 *     * `-submitted_at` - Submitted at (تنازلي)
                 *     * `reference_number` - Reference number
                 *     * `-reference_number` - Reference number (تنازلي)
                 *     * `status` - Status
                 *     * `-status` - Status (تنازلي)
                 *     * `total` - Total
                 *     * `-total` - Total (تنازلي)
                 */
                ordering?: ("-reference_number" | "-status" | "-submitted_at" | "-total" | "reference_number" | "status" | "submitted_at" | "total")[];
                /** @description رقم الصفحة ضمن النتائج المقسمة. */
                page?: number;
                /** @description عدد النتائج التي يجب إرجاعها في كل صفحة. */
                page_size?: number;
                /**
                 * @description * `NOT_UPLOADED` - لم يتم رفع الإيصال
                 *     * `PENDING_REVIEW` - بانتظار التأكيد
                 *     * `CONFIRMED` - مؤكد
                 *     * `REJECTED` - مرفوض
                 */
                payment_status?: ("CONFIRMED" | "NOT_UPLOADED" | "PENDING_REVIEW" | "REJECTED")[];
                search?: string;
                /**
                 * @description * `DRAFT` - مسودة
                 *     * `SUBMITTED` - مقدم
                 *     * `UNDER_REVIEW` - قيد المراجعة
                 *     * `NEEDS_CORRECTION` - يحتاج تصحيح
                 *     * `APPROVED` - مقبول
                 *     * `REJECTED` - مرفوض
                 */
                status?: ("APPROVED" | "DRAFT" | "NEEDS_CORRECTION" | "REJECTED" | "SUBMITTED" | "UNDER_REVIEW")[];
                sub_syndicate?: string;
                submitted_from?: string;
                submitted_to?: string;
                /**
                 * @description * `HUMAN_MEDICINE` - بشري
                 *     * `PHARMACY` - صيدلي
                 *     * `DENTISTRY` - أسنان
                 *     * `VETERINARY` - بيطري
                 */
                syndicate_type?: "DENTISTRY" | "HUMAN_MEDICINE" | "PHARMACY" | "VETERINARY";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAuditEntryList"];
                };
            };
        };
    };
    admin_applications_notes_list: {
        parameters: {
            query?: {
                fiscal_year?: number;
                /**
                 * @description * `القاهرة` - القاهرة
                 *     * `الجيزة` - الجيزة
                 *     * `الإسكندرية` - الإسكندرية
                 *     * `الدقهلية` - الدقهلية
                 *     * `البحر الأحمر` - البحر الأحمر
                 *     * `البحيرة` - البحيرة
                 *     * `الفيوم` - الفيوم
                 *     * `الغربية` - الغربية
                 *     * `الإسماعيلية` - الإسماعيلية
                 *     * `المنوفية` - المنوفية
                 *     * `المنيا` - المنيا
                 *     * `القليوبية` - القليوبية
                 *     * `الوادي الجديد` - الوادي الجديد
                 *     * `السويس` - السويس
                 *     * `أسوان` - أسوان
                 *     * `أسيوط` - أسيوط
                 *     * `بني سويف` - بني سويف
                 *     * `بورسعيد` - بورسعيد
                 *     * `دمياط` - دمياط
                 *     * `الشرقية` - الشرقية
                 *     * `جنوب سيناء` - جنوب سيناء
                 *     * `كفر الشيخ` - كفر الشيخ
                 *     * `مطروح` - مطروح
                 *     * `الأقصر` - الأقصر
                 *     * `قنا` - قنا
                 *     * `شمال سيناء` - شمال سيناء
                 *     * `سوهاج` - سوهاج
                 */
                governorate?: "أسوان" | "أسيوط" | "الأقصر" | "الإسكندرية" | "الإسماعيلية" | "البحر الأحمر" | "البحيرة" | "الجيزة" | "الدقهلية" | "السويس" | "الشرقية" | "الغربية" | "الفيوم" | "القاهرة" | "القليوبية" | "المنوفية" | "المنيا" | "الوادي الجديد" | "بني سويف" | "بورسعيد" | "جنوب سيناء" | "دمياط" | "سوهاج" | "شمال سيناء" | "قنا" | "كفر الشيخ" | "مطروح";
                /**
                 * @description الترتيب
                 *
                 *     * `submitted_at` - Submitted at
                 *     * `-submitted_at` - Submitted at (تنازلي)
                 *     * `reference_number` - Reference number
                 *     * `-reference_number` - Reference number (تنازلي)
                 *     * `status` - Status
                 *     * `-status` - Status (تنازلي)
                 *     * `total` - Total
                 *     * `-total` - Total (تنازلي)
                 */
                ordering?: ("-reference_number" | "-status" | "-submitted_at" | "-total" | "reference_number" | "status" | "submitted_at" | "total")[];
                /**
                 * @description * `NOT_UPLOADED` - لم يتم رفع الإيصال
                 *     * `PENDING_REVIEW` - بانتظار التأكيد
                 *     * `CONFIRMED` - مؤكد
                 *     * `REJECTED` - مرفوض
                 */
                payment_status?: ("CONFIRMED" | "NOT_UPLOADED" | "PENDING_REVIEW" | "REJECTED")[];
                search?: string;
                /**
                 * @description * `DRAFT` - مسودة
                 *     * `SUBMITTED` - مقدم
                 *     * `UNDER_REVIEW` - قيد المراجعة
                 *     * `NEEDS_CORRECTION` - يحتاج تصحيح
                 *     * `APPROVED` - مقبول
                 *     * `REJECTED` - مرفوض
                 */
                status?: ("APPROVED" | "DRAFT" | "NEEDS_CORRECTION" | "REJECTED" | "SUBMITTED" | "UNDER_REVIEW")[];
                sub_syndicate?: string;
                submitted_from?: string;
                submitted_to?: string;
                /**
                 * @description * `HUMAN_MEDICINE` - بشري
                 *     * `PHARMACY` - صيدلي
                 *     * `DENTISTRY` - أسنان
                 *     * `VETERINARY` - بيطري
                 */
                syndicate_type?: "DENTISTRY" | "HUMAN_MEDICINE" | "PHARMACY" | "VETERINARY";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNote"][];
                };
            };
        };
    };
    admin_applications_notes_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminNoteRequest"];
                "multipart/form-data": components["schemas"]["AdminNoteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNote"];
                };
            };
        };
    };
    admin_applications_payment_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentReviewRequest"];
                "multipart/form-data": components["schemas"]["PaymentReviewRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminApplicationDetail"];
                };
            };
        };
    };
    admin_applications_transition_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
                "multipart/form-data": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminApplicationDetail"];
                };
            };
        };
    };
    admin_doctors_list: {
        parameters: {
            query?: {
                /**
                 * @description * `القاهرة` - القاهرة
                 *     * `الجيزة` - الجيزة
                 *     * `الإسكندرية` - الإسكندرية
                 *     * `الدقهلية` - الدقهلية
                 *     * `البحر الأحمر` - البحر الأحمر
                 *     * `البحيرة` - البحيرة
                 *     * `الفيوم` - الفيوم
                 *     * `الغربية` - الغربية
                 *     * `الإسماعيلية` - الإسماعيلية
                 *     * `المنوفية` - المنوفية
                 *     * `المنيا` - المنيا
                 *     * `القليوبية` - القليوبية
                 *     * `الوادي الجديد` - الوادي الجديد
                 *     * `السويس` - السويس
                 *     * `أسوان` - أسوان
                 *     * `أسيوط` - أسيوط
                 *     * `بني سويف` - بني سويف
                 *     * `بورسعيد` - بورسعيد
                 *     * `دمياط` - دمياط
                 *     * `الشرقية` - الشرقية
                 *     * `جنوب سيناء` - جنوب سيناء
                 *     * `كفر الشيخ` - كفر الشيخ
                 *     * `مطروح` - مطروح
                 *     * `الأقصر` - الأقصر
                 *     * `قنا` - قنا
                 *     * `شمال سيناء` - شمال سيناء
                 *     * `سوهاج` - سوهاج
                 */
                governorate?: "أسوان" | "أسيوط" | "الأقصر" | "الإسكندرية" | "الإسماعيلية" | "البحر الأحمر" | "البحيرة" | "الجيزة" | "الدقهلية" | "السويس" | "الشرقية" | "الغربية" | "الفيوم" | "القاهرة" | "القليوبية" | "المنوفية" | "المنيا" | "الوادي الجديد" | "بني سويف" | "بورسعيد" | "جنوب سيناء" | "دمياط" | "سوهاج" | "شمال سيناء" | "قنا" | "كفر الشيخ" | "مطروح";
                /** @description رقم الصفحة ضمن النتائج المقسمة. */
                page?: number;
                /** @description عدد النتائج التي يجب إرجاعها في كل صفحة. */
                page_size?: number;
                search?: string;
                /**
                 * @description * `HUMAN_MEDICINE` - بشري
                 *     * `PHARMACY` - صيدلي
                 *     * `DENTISTRY` - أسنان
                 *     * `VETERINARY` - بيطري
                 */
                syndicate_type?: "DENTISTRY" | "HUMAN_MEDICINE" | "PHARMACY" | "VETERINARY";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminDoctorRowList"];
                };
            };
        };
    };
    admin_doctors_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDoctorDetail"];
                };
            };
        };
    };
    admin_fee_schedules_list: {
        parameters: {
            query?: {
                /** @description رقم الصفحة ضمن النتائج المقسمة. */
                page?: number;
                /** @description عدد النتائج التي يجب إرجاعها في كل صفحة. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFeeScheduleList"];
                };
            };
        };
    };
    admin_fee_schedules_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeeScheduleRequest"];
                "multipart/form-data": components["schemas"]["FeeScheduleRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeSchedule"];
                };
            };
        };
    };
    admin_fee_schedules_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeSchedule"];
                };
            };
        };
    };
    admin_stats: {
        parameters: {
            query?: {
                fiscal_year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStats"];
                };
            };
        };
    };
    applications_list: {
        parameters: {
            query?: {
                /** @description رقم الصفحة ضمن النتائج المقسمة. */
                page?: number;
                /** @description عدد النتائج التي يجب إرجاعها في كل صفحة. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedApplicationList"];
                };
            };
        };
    };
    applications_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApplicationCreateRequest"];
                "multipart/form-data": components["schemas"]["ApplicationCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_beneficiaries_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beneficiary"][];
                };
            };
        };
    };
    applications_beneficiaries_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BeneficiaryWriteRequest"];
                "multipart/form-data": components["schemas"]["BeneficiaryWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beneficiary"];
                };
            };
        };
    };
    applications_beneficiaries_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    applications_beneficiaries_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBeneficiaryWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedBeneficiaryWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Beneficiary"];
                };
            };
        };
    };
    documents_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["DocumentUploadRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"];
                };
            };
        };
    };
    applications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedApplicationUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedApplicationUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_fees_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    applications_submit_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    applications_validation_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description session created, redirect to the SPA */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_dev_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
                "multipart/form-data": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_dev_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevUser"][];
                };
            };
        };
    };
    auth_login: {
        parameters: {
            query?: {
                /** @description relative SPA path */
                next?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description redirect to Entra External ID */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Logout"];
                };
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"];
                };
            };
        };
    };
    documents_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    documents_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description redirect to a read-only SAS URL (≤5 minutes) */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    documents_extract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OcrSuggestion"];
                };
            };
        };
    };
    profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorProfile"];
                };
            };
        };
    };
    profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDoctorProfileRequest"];
                "multipart/form-data": components["schemas"]["PatchedDoctorProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorProfile"];
                };
            };
        };
    };
    reference_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
