# Generated by Django 5.2.17 on 2026-10-05 09:02

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("APPLICATION_CREATED", "Application Created"),
                            ("APPLICATION_SUBMITTED", "Application Submitted"),
                            ("APPLICATION_RESUBMITTED", "Application Resubmitted"),
                            ("APPLICATION_STATUS_CHANGED", "Application Status Changed"),
                            ("PAYMENT_STATUS_CHANGED", "Payment Status Changed"),
                            ("FEE_SNAPSHOT_CREATED", "Fee Snapshot Created"),
                            ("DOCUMENT_UPLOADED", "Document Uploaded"),
                            ("DOCUMENT_REPLACED", "Document Replaced"),
                            ("DOCUMENT_DELETED", "Document Deleted"),
                            ("DOCUMENT_VIEWED", "Document Viewed"),
                            ("OCR_REQUESTED", "Ocr Requested"),
                            ("ADMIN_APPLICATION_VIEWED", "Admin Application Viewed"),
                            ("ADMIN_NOTE_ADDED", "Admin Note Added"),
                            ("FEE_SCHEDULE_CHANGED", "Fee Schedule Changed"),
                            ("ADMIN_ROLE_GRANTED", "Admin Role Granted"),
                            ("NATIONAL_ID_REVEALED", "National Id Revealed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("object_type", models.CharField(max_length=64)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id", "timestamp"], name="audit_object_idx"
                    ),
                    models.Index(fields=["action", "timestamp"], name="audit_action_idx"),
                    models.Index(fields=["user", "timestamp"], name="audit_user_idx"),
                ],
            },
        ),
    ]
