# Generated by Django 5.2.17 on 2026-10-05 09:02

import uuid

import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models

import apps.accounts.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[("DOCTOR", "طبيب"), ("ADMIN", "مسؤول")],
                        default="DOCTOR",
                        max_length=16,
                    ),
                ),
                ("entra_oid", models.CharField(blank=True, max_length=64, null=True)),
                ("entra_tid", models.CharField(blank=True, max_length=64, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("email",), name="uniq_user_email"),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"), name="uniq_user_email_ci"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("entra_oid__isnull", False)),
                        fields=("entra_oid", "entra_tid"),
                        name="uniq_user_entra_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["DOCTOR", "ADMIN"])),
                        name="user_role_valid",
                    ),
                ],
            },
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
    ]
