# Generated by Django 5.2.17 on 2026-10-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, db_default="", default="", max_length=200),
        ),
    ]
