# Generated by Django 5.2.17 on 2026-10-05 09:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("fees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fiscal_year", models.PositiveSmallIntegerField(unique=True)),
                ("last_sequence", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fiscal_year", models.PositiveSmallIntegerField()),
                (
                    "application_type",
                    models.CharField(
                        choices=[("FIRST_TIME", "أول مرة"), ("ADDITION", "إضافة")],
                        default="FIRST_TIME",
                        max_length=16,
                    ),
                ),
                (
                    "work_status",
                    models.CharField(
                        blank=True,
                        choices=[("WORKING", "يعمل"), ("PENSIONER", "معاش"), ("DECEASED", "متوفى")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("SUBMITTED", "مقدم"),
                            ("UNDER_REVIEW", "قيد المراجعة"),
                            ("NEEDS_CORRECTION", "يحتاج تصحيح"),
                            ("APPROVED", "مقبول"),
                            ("REJECTED", "مرفوض"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("NOT_UPLOADED", "لم يتم رفع الإيصال"),
                            ("PENDING_REVIEW", "بانتظار التأكيد"),
                            ("CONFIRMED", "مؤكد"),
                            ("REJECTED", "مرفوض"),
                        ],
                        default="NOT_UPLOADED",
                        max_length=16,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("declaration_name", models.CharField(blank=True, max_length=200)),
                ("declaration_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("fee_snapshot", models.JSONField(blank=True, null=True)),
                ("submitted_snapshot", models.JSONField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "fee_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="fees.feeschedule",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_notes",
                        to="applications.insuranceapplication",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="insuranceapplication",
            index=models.Index(fields=["status", "submitted_at"], name="app_status_submitted_idx"),
        ),
        migrations.AddIndex(
            model_name="insuranceapplication",
            index=models.Index(fields=["fiscal_year", "status"], name="app_year_status_idx"),
        ),
        migrations.AddIndex(
            model_name="insuranceapplication",
            index=models.Index(fields=["payment_status"], name="app_payment_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="insuranceapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "REJECTED"), _negated=True),
                fields=("doctor", "fiscal_year"),
                name="uniq_active_application_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="insuranceapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "DRAFT",
                            "SUBMITTED",
                            "UNDER_REVIEW",
                            "NEEDS_CORRECTION",
                            "APPROVED",
                            "REJECTED",
                        ],
                    )
                ),
                name="app_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="insuranceapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "payment_status__in",
                        ["NOT_UPLOADED", "PENDING_REVIEW", "CONFIRMED", "REJECTED"],
                    )
                ),
                name="app_payment_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="insuranceapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("application_type__in", ["FIRST_TIME", "ADDITION"])),
                name="app_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="insuranceapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("work_status", ""),
                    ("work_status__in", ["WORKING", "PENSIONER", "DECEASED"]),
                    _connector="OR",
                ),
                name="app_work_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="insuranceapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reference_number__isnull", True), ("status", "DRAFT")),
                    models.Q(
                        models.Q(("status", "DRAFT"), _negated=True),
                        ("reference_number__isnull", False),
                        ("reference_number__regex", "^MED-[0-9]{4}-[0-9]{6}$"),
                    ),
                    _connector="OR",
                ),
                name="app_reference_number_iff_submitted",
            ),
        ),
        migrations.AddIndex(
            model_name="adminnote",
            index=models.Index(
                fields=["application", "created_at"], name="adminnote_app_created_idx"
            ),
        ),
    ]
