# Generated by Django 5.2.17 on 2026-10-05 09:02

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("beneficiaries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("NATIONAL_ID_FRONT", "صورة البطاقة (وجه)"),
                            ("NATIONAL_ID_BACK", "صورة البطاقة (ظهر)"),
                            ("SYNDICATE_ID", "كارنيه النقابة"),
                            ("PERSONAL_PHOTO", "صورة العضو الأصلي"),
                            ("PAYMENT_RECEIPT", "إيصال الدفع"),
                            ("BENEFICIARY_NATIONAL_ID", "بطاقة الرقم القومي"),
                            ("BIRTH_CERTIFICATE", "شهادة الميلاد"),
                            ("MARRIAGE_CERTIFICATE", "شهادة الزواج"),
                            ("INSURANCE_PRINT", "برينت تأميني"),
                            ("UNIVERSITY_ID", "كارنيه الجامعة"),
                            ("OTHER", "مستند آخر"),
                        ],
                        max_length=32,
                    ),
                ),
                ("blob_name", models.CharField(max_length=400)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("file_size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد الفحص"),
                            ("CLEAN", "سليم"),
                            ("INFECTED", "مصاب"),
                            ("SKIPPED", "لم يتم الفحص"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="applications.insuranceapplication",
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="beneficiaries.beneficiary",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        condition=models.Q(("deleted_at__isnull", False)),
                        fields=["deleted_at"],
                        name="document_deleted_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("blob_name",), name="uniq_document_blob_name"),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("application", "beneficiary", "document_type"),
                        name="uniq_active_document_per_slot",
                        nulls_distinct=False,
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", False),
                            models.Q(
                                ("beneficiary__isnull", True),
                                (
                                    "document_type__in",
                                    (
                                        "NATIONAL_ID_FRONT",
                                        "NATIONAL_ID_BACK",
                                        "SYNDICATE_ID",
                                        "PERSONAL_PHOTO",
                                        "PAYMENT_RECEIPT",
                                    ),
                                ),
                            ),
                            models.Q(
                                ("beneficiary__isnull", False),
                                (
                                    "document_type__in",
                                    (
                                        "BENEFICIARY_NATIONAL_ID",
                                        "BIRTH_CERTIFICATE",
                                        "MARRIAGE_CERTIFICATE",
                                        "INSURANCE_PRINT",
                                        "UNIVERSITY_ID",
                                    ),
                                ),
                            ),
                            ("document_type", "OTHER"),
                            _connector="OR",
                        ),
                        name="document_type_matches_owner",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("scan_status__in", ["PENDING", "CLEAN", "INFECTED", "SKIPPED"])
                        ),
                        name="document_scan_status_valid",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
