# Generated by Django 5.2.17 on 2026-10-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="blob_purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
