# Generated by Django 5.2.17 on 2026-10-05 09:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("national_id", models.CharField(blank=True, max_length=14, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("birth_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("MALE", "ذكر"), ("FEMALE", "أنثى")], max_length=8
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        blank=True,
                        choices=[("MUSLIM", "مسلم"), ("CHRISTIAN", "مسيحي")],
                        max_length=16,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=16)),
                (
                    "syndicate_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HUMAN_MEDICINE", "بشري"),
                            ("PHARMACY", "صيدلي"),
                            ("DENTISTRY", "أسنان"),
                            ("VETERINARY", "بيطري"),
                        ],
                        max_length=16,
                    ),
                ),
                ("sub_syndicate", models.CharField(blank=True, max_length=100)),
                ("syndicate_registration_number", models.CharField(blank=True, max_length=32)),
                (
                    "syndicate_registration_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("treatment_card_number", models.CharField(blank=True, max_length=32)),
                ("governorate", models.CharField(blank=True, max_length=32)),
                ("neighborhood", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["syndicate_type", "syndicate_registration_number"],
                        name="doctor_syndicate_regno_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("national_id",), name="uniq_doctor_national_id"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("national_id__isnull", True),
                            ("national_id__regex", "^[23][0-9]{13}$"),
                            _connector="OR",
                        ),
                        name="doctor_national_id_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("gender", ""), ("gender__in", ["MALE", "FEMALE"]), _connector="OR"
                        ),
                        name="doctor_gender_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("syndicate_type", ""),
                            (
                                "syndicate_type__in",
                                ["HUMAN_MEDICINE", "PHARMACY", "DENTISTRY", "VETERINARY"],
                            ),
                            _connector="OR",
                        ),
                        name="doctor_syndicate_type_valid",
                    ),
                ],
            },
        ),
    ]
