# Generated by Django 5.2.17 on 2026-10-05 09:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("row_number", models.PositiveSmallIntegerField()),
                (
                    "kinship",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MOTHER", "أم"),
                            ("FATHER", "أب"),
                            ("SON_MINOR", "ابن (18 سنة أو أقل)"),
                            ("SON_UNIVERSITY", "ابن (طالب جامعي)"),
                            ("SON_GRADUATE", "ابن (خريج)"),
                            ("DAUGHTER", "ابنة"),
                            ("HUSBAND", "زوج"),
                            ("WIFE", "زوجة"),
                        ],
                        max_length=16,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("birth_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("national_id", models.CharField(blank=True, max_length=14, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiaries",
                        to="applications.insuranceapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("national_id__isnull", False)),
                        fields=["national_id"],
                        name="beneficiary_national_id_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "row_number"), name="uniq_beneficiary_row"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("national_id__isnull", False)),
                        fields=("application", "national_id"),
                        name="uniq_beneficiary_national_id_per_application",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("row_number__gte", 1), ("row_number__lte", 20)),
                        name="beneficiary_row_number_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("national_id__isnull", True),
                            ("national_id__regex", "^[23][0-9]{13}$"),
                            _connector="OR",
                        ),
                        name="beneficiary_national_id_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kinship", ""),
                            (
                                "kinship__in",
                                [
                                    "MOTHER",
                                    "FATHER",
                                    "SON_MINOR",
                                    "SON_UNIVERSITY",
                                    "SON_GRADUATE",
                                    "DAUGHTER",
                                    "HUSBAND",
                                    "WIFE",
                                ],
                            ),
                            _connector="OR",
                        ),
                        name="beneficiary_kinship_valid",
                    ),
                ],
            },
        ),
    ]
