# Generated by Django 5.2.17 on 2026-10-05 09:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.fees.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("fiscal_year", models.PositiveSmallIntegerField()),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("tier_fees", models.JSONField(validators=[apps.fees.models.validate_tier_fees])),
                (
                    "tier_boundaries",
                    models.JSONField(
                        default=list, validators=[apps.fees.models.validate_tier_boundaries]
                    ),
                ),
                ("admin_fee_member_only", models.PositiveIntegerField(default=150)),
                ("admin_fee_with_beneficiaries", models.PositiveIntegerField(default=175)),
                ("age_cap_threshold", models.PositiveSmallIntegerField(default=70)),
                ("age_cap_amount", models.PositiveIntegerField(default=500)),
                ("registration_year_min", models.PositiveSmallIntegerField(default=1950)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fiscal_year", "version"), name="uniq_fee_schedule_version"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("fiscal_year",),
                        name="uniq_active_fee_schedule_per_year",
                    ),
                ],
            },
        ),
    ]
